library(ggplot2)
library(data.table)
library(dplyr)
library(tidyverse)
options(java.parameters = "- Xmx8192m")
library(extrafont)
loadfonts(device="win")
require(moonBook)
require(webr)
library(grid)
library(lemon)
library(lawstat)
library(agricolae)
library(PMCMR)
library(PMCMRplus)
library(PerformanceAnalytics)
library(ggrepel)
library(ggsci)
library(tidyr)
library("scales")
library(multcompView)
library(DescTools)
library(lawstat)
library(vegan)
library(ggpubr)
library(ggtext)
library(VennDiagram)
library("ggVennDiagram")
library(ggforce)
library(VIM)
library(naniar)
library(missMDA)
library(Amelia)
library(mice)
library(missForest)
library(FactoMineR)
library(mixOmics)
library(RVAideMemoire)
Sys.setlocale("LC_TIME","english")
library(openair)
library(tidyverse)
library(lubridate)
library(worldmet)
library(openairmaps)
library("scales")
library(dendextend)
library(cowplot)
library(xlsx)
library(data.table)
library(dplyr)
library(openxlsx)
library(indicspecies)
library(labdsv)
library(readr)
library(sf)
# for plotting
library(leaflet)
library(leaflet.extras)
# for more stuff
library(geosphere)
library(magrittr)
library(plotly)
library(ggnewscale)
library(cowplot)
library(ggalluvial)
library(patchwork)
library(corrplot)
library(ggcorrplot)
library(FD)
library(PerformanceAnalytics)
library(rayshader)
library(ggh4x)
library(spData)
library(viridis)
library(tmap)



#not installed
Sys.setlocale("LC_TIME","english")
options(digits=10) # Sig figs in mass resolution data


source("Rscript/func_filename.R")
source("Rscript/func_generate_lable.R")
source("Rscript/func_upper_fence_label.R")
#source("Rscript/piedonut_ms.R")
insert_minor_1 <- function(major_labs, n_minor) {labs <- 
  c( sapply( major_labs, function(x) c(x, rep("", 4) ) ) )
labs[1:(length(labs)-n_minor)]}

insert_minor_2 <- function(major_labs, n_minor) {labs <- 
  c( sapply( major_labs, function(x) c(x, rep("", 1) ) ) )
labs[1:(length(labs)-n_minor)]}

